title: junhoyeo
email: hanaro0704@gmail.com
baseurl: ""
url: "https://junhoyeo.github.io/"

collections:
  projects:
  # tags:

sass:
  sass_dir: _scss
  style: compressed

owner:
  name: 여준호
  intro:
    - IT를 사용해서 세상에 어떤 방식으로든 기여하는 사람이 되고자 노력 중인 고등학생입니다.
    - 함께 일하기 좋은, 트렌디한 개발자가 되고 싶습니다.
  github: junhoyeo
  facebook: juno3704
  profile: /assets/images/profile.png

g-analytics: UA-143434538-1

markdown: kramdown
plugins:
  - jekyll-feed
